// Code generated by go-swagger; DO NOT EDIT.

package clinics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutClinicsClinicGUIDParams creates a new PutClinicsClinicGUIDParams object
// with the default values initialized.
func NewPutClinicsClinicGUIDParams() *PutClinicsClinicGUIDParams {
	var ()
	return &PutClinicsClinicGUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutClinicsClinicGUIDParamsWithTimeout creates a new PutClinicsClinicGUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutClinicsClinicGUIDParamsWithTimeout(timeout time.Duration) *PutClinicsClinicGUIDParams {
	var ()
	return &PutClinicsClinicGUIDParams{

		timeout: timeout,
	}
}

// NewPutClinicsClinicGUIDParamsWithContext creates a new PutClinicsClinicGUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutClinicsClinicGUIDParamsWithContext(ctx context.Context) *PutClinicsClinicGUIDParams {
	var ()
	return &PutClinicsClinicGUIDParams{

		Context: ctx,
	}
}

// NewPutClinicsClinicGUIDParamsWithHTTPClient creates a new PutClinicsClinicGUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutClinicsClinicGUIDParamsWithHTTPClient(client *http.Client) *PutClinicsClinicGUIDParams {
	var ()
	return &PutClinicsClinicGUIDParams{
		HTTPClient: client,
	}
}

/*PutClinicsClinicGUIDParams contains all the parameters to send to the API endpoint
for the put clinics clinic GUID operation typically these are written to a http.Request
*/
type PutClinicsClinicGUIDParams struct {

	/*Body*/
	Body PutClinicsClinicGUIDBody
	/*ClinicGUID
	  GUID клиники

	*/
	ClinicGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) WithTimeout(timeout time.Duration) *PutClinicsClinicGUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) WithContext(ctx context.Context) *PutClinicsClinicGUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) WithHTTPClient(client *http.Client) *PutClinicsClinicGUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) WithBody(body PutClinicsClinicGUIDBody) *PutClinicsClinicGUIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) SetBody(body PutClinicsClinicGUIDBody) {
	o.Body = body
}

// WithClinicGUID adds the clinicGUID to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) WithClinicGUID(clinicGUID string) *PutClinicsClinicGUIDParams {
	o.SetClinicGUID(clinicGUID)
	return o
}

// SetClinicGUID adds the clinicGuid to the put clinics clinic GUID params
func (o *PutClinicsClinicGUIDParams) SetClinicGUID(clinicGUID string) {
	o.ClinicGUID = clinicGUID
}

// WriteToRequest writes these params to a swagger request
func (o *PutClinicsClinicGUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param clinicGUID
	if err := r.SetPathParam("clinicGUID", o.ClinicGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
