// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostClientOKCode is the HTTP code returned for type PostClientOK
const PostClientOKCode int = 200

/*PostClientOK Результат аутентификации

swagger:response postClientOK
*/
type PostClientOK struct {

	/*
	  In: Body
	*/
	Payload *PostClientOKBody `json:"body,omitempty"`
}

// NewPostClientOK creates PostClientOK with default headers values
func NewPostClientOK() *PostClientOK {

	return &PostClientOK{}
}

// WithPayload adds the payload to the post client o k response
func (o *PostClientOK) WithPayload(payload *PostClientOKBody) *PostClientOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post client o k response
func (o *PostClientOK) SetPayload(payload *PostClientOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostClientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostClientUnauthorizedCode is the HTTP code returned for type PostClientUnauthorized
const PostClientUnauthorizedCode int = 401

/*PostClientUnauthorized Access denied

swagger:response postClientUnauthorized
*/
type PostClientUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *PostClientUnauthorizedBody `json:"body,omitempty"`
}

// NewPostClientUnauthorized creates PostClientUnauthorized with default headers values
func NewPostClientUnauthorized() *PostClientUnauthorized {

	return &PostClientUnauthorized{}
}

// WithPayload adds the payload to the post client unauthorized response
func (o *PostClientUnauthorized) WithPayload(payload *PostClientUnauthorizedBody) *PostClientUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post client unauthorized response
func (o *PostClientUnauthorized) SetPayload(payload *PostClientUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostClientUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostClientMethodNotAllowedCode is the HTTP code returned for type PostClientMethodNotAllowed
const PostClientMethodNotAllowedCode int = 405

/*PostClientMethodNotAllowed Invalid Method

swagger:response postClientMethodNotAllowed
*/
type PostClientMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *PostClientMethodNotAllowedBody `json:"body,omitempty"`
}

// NewPostClientMethodNotAllowed creates PostClientMethodNotAllowed with default headers values
func NewPostClientMethodNotAllowed() *PostClientMethodNotAllowed {

	return &PostClientMethodNotAllowed{}
}

// WithPayload adds the payload to the post client method not allowed response
func (o *PostClientMethodNotAllowed) WithPayload(payload *PostClientMethodNotAllowedBody) *PostClientMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post client method not allowed response
func (o *PostClientMethodNotAllowed) SetPayload(payload *PostClientMethodNotAllowedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostClientMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostClientInternalServerErrorCode is the HTTP code returned for type PostClientInternalServerError
const PostClientInternalServerErrorCode int = 500

/*PostClientInternalServerError Internal server error

swagger:response postClientInternalServerError
*/
type PostClientInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostClientInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostClientInternalServerError creates PostClientInternalServerError with default headers values
func NewPostClientInternalServerError() *PostClientInternalServerError {

	return &PostClientInternalServerError{}
}

// WithPayload adds the payload to the post client internal server error response
func (o *PostClientInternalServerError) WithPayload(payload *PostClientInternalServerErrorBody) *PostClientInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post client internal server error response
func (o *PostClientInternalServerError) SetPayload(payload *PostClientInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostClientInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
