// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostOauth2BackendIDConsentParams creates a new PostOauth2BackendIDConsentParams object
// no default values defined in spec.
func NewPostOauth2BackendIDConsentParams() PostOauth2BackendIDConsentParams {

	return PostOauth2BackendIDConsentParams{}
}

// PostOauth2BackendIDConsentParams contains all the bound params for the post oauth2 backend ID consent operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostOauth2BackendIDConsent
type PostOauth2BackendIDConsentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Идентификатор бэкенда
	  Required: true
	  In: path
	*/
	BackendID string
	/*
	  In: body
	*/
	Body PostOauth2BackendIDConsentBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostOauth2BackendIDConsentParams() beforehand.
func (o *PostOauth2BackendIDConsentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBackendID, rhkBackendID, _ := route.Params.GetOK("backendID")
	if err := o.bindBackendID(rBackendID, rhkBackendID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostOauth2BackendIDConsentBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBackendID binds and validates parameter BackendID from path.
func (o *PostOauth2BackendIDConsentParams) bindBackendID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.BackendID = raw

	return nil
}
