// Code generated by go-swagger; DO NOT EDIT.

package appointment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAppointmentViewParams creates a new AppointmentViewParams object
// no default values defined in spec.
func NewAppointmentViewParams() AppointmentViewParams {

	return AppointmentViewParams{}
}

// AppointmentViewParams contains all the bound params for the appointment view operation
// typically these are obtained from a http.Request
//
// swagger:parameters AppointmentView
type AppointmentViewParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Идентификатор медицинского назначения
	  Required: true
	  In: path
	*/
	AppointmentID strfmt.UUID
	/*Идентификатор пользователя
	  Required: true
	  In: path
	*/
	UserID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAppointmentViewParams() beforehand.
func (o *AppointmentViewParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAppointmentID, rhkAppointmentID, _ := route.Params.GetOK("appointmentID")
	if err := o.bindAppointmentID(rAppointmentID, rhkAppointmentID, route.Formats); err != nil {
		res = append(res, err)
	}

	rUserID, rhkUserID, _ := route.Params.GetOK("userID")
	if err := o.bindUserID(rUserID, rhkUserID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAppointmentID binds and validates parameter AppointmentID from path.
func (o *AppointmentViewParams) bindAppointmentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("appointmentID", "path", "strfmt.UUID", raw)
	}
	o.AppointmentID = *(value.(*strfmt.UUID))

	if err := o.validateAppointmentID(formats); err != nil {
		return err
	}

	return nil
}

// validateAppointmentID carries on validations for parameter AppointmentID
func (o *AppointmentViewParams) validateAppointmentID(formats strfmt.Registry) error {

	if err := validate.FormatOf("appointmentID", "path", "uuid", o.AppointmentID.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindUserID binds and validates parameter UserID from path.
func (o *AppointmentViewParams) bindUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("userID", "path", "strfmt.UUID", raw)
	}
	o.UserID = *(value.(*strfmt.UUID))

	if err := o.validateUserID(formats); err != nil {
		return err
	}

	return nil
}

// validateUserID carries on validations for parameter UserID
func (o *AppointmentViewParams) validateUserID(formats strfmt.Registry) error {

	if err := validate.FormatOf("userID", "path", "uuid", o.UserID.String(), formats); err != nil {
		return err
	}
	return nil
}
