// Code generated by go-swagger; DO NOT EDIT.

package replies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReplyPutParams creates a new ReplyPutParams object
// no default values defined in spec.
func NewReplyPutParams() ReplyPutParams {

	return ReplyPutParams{}
}

// ReplyPutParams contains all the bound params for the reply put operation
// typically these are obtained from a http.Request
//
// swagger:parameters replyPut
type ReplyPutParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Body ReplyPutBody
	/*Идентификатор ответа
	  Required: true
	  In: path
	*/
	ReplyID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewReplyPutParams() beforehand.
func (o *ReplyPutParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body ReplyPutBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	rReplyID, rhkReplyID, _ := route.Params.GetOK("replyID")
	if err := o.bindReplyID(rReplyID, rhkReplyID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindReplyID binds and validates parameter ReplyID from path.
func (o *ReplyPutParams) bindReplyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("replyID", "path", "strfmt.UUID", raw)
	}
	o.ReplyID = *(value.(*strfmt.UUID))

	if err := o.validateReplyID(formats); err != nil {
		return err
	}

	return nil
}

// validateReplyID carries on validations for parameter ReplyID
func (o *ReplyPutParams) validateReplyID(formats strfmt.Registry) error {

	if err := validate.FormatOf("replyID", "path", "uuid", o.ReplyID.String(), formats); err != nil {
		return err
	}
	return nil
}
