// Code generated by go-swagger; DO NOT EDIT.

package replies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReplyDeleteParams creates a new ReplyDeleteParams object
// no default values defined in spec.
func NewReplyDeleteParams() ReplyDeleteParams {

	return ReplyDeleteParams{}
}

// ReplyDeleteParams contains all the bound params for the reply delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters replyDelete
type ReplyDeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Идентификатор ответа
	  Required: true
	  In: path
	*/
	ReplyID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewReplyDeleteParams() beforehand.
func (o *ReplyDeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rReplyID, rhkReplyID, _ := route.Params.GetOK("replyID")
	if err := o.bindReplyID(rReplyID, rhkReplyID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindReplyID binds and validates parameter ReplyID from path.
func (o *ReplyDeleteParams) bindReplyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("replyID", "path", "strfmt.UUID", raw)
	}
	o.ReplyID = *(value.(*strfmt.UUID))

	if err := o.validateReplyID(formats); err != nil {
		return err
	}

	return nil
}

// validateReplyID carries on validations for parameter ReplyID
func (o *ReplyDeleteParams) validateReplyID(formats strfmt.Registry) error {

	if err := validate.FormatOf("replyID", "path", "uuid", o.ReplyID.String(), formats); err != nil {
		return err
	}
	return nil
}
