version: '3'

networks:
  diacare:
    external: true

volumes:
  mongo:
  influx:

services:
  datarouter_api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        _path: cmd/datarouter
    container_name: "datarouter_api"
    networks:
      - diacare
    ports:
      - 8787:80
    depends_on:
      - datarouter_config_db
      - datarouter_event_db
    environment:
      - DATAROUTER_HTTP_HOST=0.0.0.0
      - DATAROUTER_HTTP_PORT=80
      - DATAROUTER_CONFIGDB_HOST=datarouter_config_db
      - DATAROUTER_CONFIGDB_PORT=27017
      - DATAROUTER_CONFIGDB_DATABASE=data_router
      - DATAROUTER_SENTRYDSN=https://6e4933fa655f4d12ab85f66fc0dc8f5f@sentry.diacare-soft.ru/5
      - DATAROUTER_LOGGING_OUTPUT=STDOUT
      - DATAROUTER_LOGGING_LEVEL=INFO
      - DATAROUTER_EVENTDB_HOST=datarouter_event_db
      - DATAROUTER_EVENTDB_PORT=8086
      - DATAROUTER_EVENTDB_PROTOCOL=http
      - DATAROUTER_EVENTDB_DATABASE=data_router
      - DATAROUTER_EVENTDB_LOGIN=data_router
      - DATAROUTER_EVENTDB_PASSWORD=FqTfXq7e5d

  datarouter_proxy:
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        _path: cmd/proxy
    container_name: "datarouter_proxy"
    networks:
      - diacare
    ports:
      - 8040
    depends_on:
      - datarouter_config_db
      - datarouter_broker
      - datarouter_event_db
    environment:
      - DATAROUTER_CONFIGDB_HOST=datarouter_config_db
      - DATAROUTER_CONFIGDB_PORT=27017
      - DATAROUTER_CONFIGDB_DATABASE=data_router
      - DATAROUTER_EVENTDB_HOST=datarouter_event_db
      - DATAROUTER_EVENTDB_PORT=8086
      - DATAROUTER_EVENTDB_PROTOCOL=http
      - DATAROUTER_EVENTDB_DATABASE=data_router
      - DATAROUTER_EVENTDB_LOGIN=data_router
      - DATAROUTER_EVENTDB_PASSWORD=FqTfXq7e5d
      - DATAROUTER_SENTRYDSN=https://6e4933fa655f4d12ab85f66fc0dc8f5f@sentry.diacare-soft.ru/5
      - DATAROUTER_LOGGING_OUTPUT=STDOUT
      - DATAROUTER_LOGGING_LEVEL=INFO
      - DATAROUTER_LOGGING_FORMAT=TEXT
      - DATAROUTER_PROMETHEUS_PORT=9100
      - DATAROUTER_PROMETHEUS_PATH=/metrics
      - DATAROUTER_MQ_HOST=datarouter_broker
      - DATAROUTER_MQ_PORT=1883
      - DATAROUTER_MQ_LOGIN=datarouter
      - DATAROUTER_MQ_PASSWORD=kw2D0gW6jD
      - DATAROUTER_MQ_PUBCLIENTID=publisher_dataRouterID
      - DATAROUTER_MQ_SUBCLIENTID=subscriber_dataRouterID
      - DATAROUTER_MQ_SUBSCRIBE=services/+/OUT

  datarouter_config_db:
    image: mongo
    container_name: "datarouter_config_db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - diacare
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    logging:
      driver: none


  datarouter_event_db:
    image: influxdb:1.7
    container_name: "datarouter_event_db"
    networks:
      - diacare
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=data_router
      - INFLUXDB_USER=data_router
      - INFLUXDB_USER_PASSWORD=FqTfXq7e5d
    volumes:
      - influx:/var/lib/influxdb
    logging:
      driver: none

  #localhost:8888 - GUI
  datarouter_chronograf:
    image: chronograf:latest
    restart: always
    container_name: "datarouter_chronograf"
    networks:
      - diacare
    depends_on:
      - datarouter_event_db
    ports:
      - 8888:8888
    logging:
      driver: none

  datarouter_broker:
    image: erlio/docker-vernemq:1.8.0
    restart: always
    container_name: "datarouter_broker"
    networks:
      - diacare
    ports:
      - 1883:1883
    environment:
      - DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=info
      - DOCKER_VERNEMQ_QUEUE_DELIVER_MODE=balance
      # Login
      - DOCKER_VERNEMQ_USER_datarouter=kw2D0gW6jD
    logging:
      driver: none

  mock_proxy:
    build:
      context: ./
      dockerfile: cmd/mock/Dockerfile
      args:
        _path: cmd/mock
    container_name: "mock_proxy"
    networks:
      - diacare
    ports:
      - 9393:80
    depends_on:
      - datarouter_config_db
      - datarouter_broker
      - datarouter_event_db
    environment:
      - DATAROUTER_CONFIGDB_HOST=datarouter_config_db
      - DATAROUTER_CONFIGDB_PORT=27017
      - DATAROUTER_CONFIGDB_DATABASE=data_router
      - DATAROUTER_EVENTDB_HOST=datarouter_event_db
      - DATAROUTER_EVENTDB_PORT=8086
      - DATAROUTER_EVENTDB_PROTOCOL=http
      - DATAROUTER_EVENTDB_DATABASE=data_router
      - DATAROUTER_EVENTDB_LOGIN=data_router
      - DATAROUTER_EVENTDB_PASSWORD=FqTfXq7e5d
      - DATAROUTER_LOGGING_OUTPUT=STDOUT
      - DATAROUTER_LOGGING_LEVEL=DEBUG
      - DATAROUTER_LOGGING_FORMAT=TEXT
      - DATAROUTER_MQ_HOST=datarouter_broker
      - DATAROUTER_MQ_PORT=1883
      - DATAROUTER_MQ_LOGIN=datarouter
      - DATAROUTER_MQ_PASSWORD=kw2D0gW6jD
      - DATAROUTER_MQ_PUBCLIENTID=publisher_dataRouterID
      - DATAROUTER_MQ_SUBCLIENTID=subscriber_dataRouterID
      - DATAROUTER_MQ_SUBSCRIBE=services/mock/OUT
