// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"repo.nefrosovet.ru/maximus-platform/auth/index/client/auth"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/clinic_employees"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/clinics"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/departments"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/employees"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/patients"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/search"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/services"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/status"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/treatment_episodes"
	"repo.nefrosovet.ru/maximus-platform/auth/index/client/utils"
)

// Default index HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "index.maximus.lan"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new index HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Index {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new index HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Index {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new index client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Index {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Index)
	cli.Transport = transport

	cli.Auth = auth.New(transport, formats)

	cli.ClinicEmployees = clinic_employees.New(transport, formats)

	cli.Clinics = clinics.New(transport, formats)

	cli.Departments = departments.New(transport, formats)

	cli.Employees = employees.New(transport, formats)

	cli.Patients = patients.New(transport, formats)

	cli.Search = search.New(transport, formats)

	cli.Services = services.New(transport, formats)

	cli.Status = status.New(transport, formats)

	cli.TreatmentEpisodes = treatment_episodes.New(transport, formats)

	cli.Utils = utils.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Index is a client for index
type Index struct {
	Auth *auth.Client

	ClinicEmployees *clinic_employees.Client

	Clinics *clinics.Client

	Departments *departments.Client

	Employees *employees.Client

	Patients *patients.Client

	Search *search.Client

	Services *services.Client

	Status *status.Client

	TreatmentEpisodes *treatment_episodes.Client

	Utils *utils.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Index) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Auth.SetTransport(transport)

	c.ClinicEmployees.SetTransport(transport)

	c.Clinics.SetTransport(transport)

	c.Departments.SetTransport(transport)

	c.Employees.SetTransport(transport)

	c.Patients.SetTransport(transport)

	c.Search.SetTransport(transport)

	c.Services.SetTransport(transport)

	c.Status.SetTransport(transport)

	c.TreatmentEpisodes.SetTransport(transport)

	c.Utils.SetTransport(transport)

}
