// Code generated by go-swagger; DO NOT EDIT.

package j_w_k

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetJwkOKCode is the HTTP code returned for type GetJwkOK
const GetJwkOKCode int = 200

/*GetJwkOK Информация о ключах подписи токенов

swagger:response getJwkOK
*/
type GetJwkOK struct {

	/*
	  In: Body
	*/
	Payload *GetJwkOKBody `json:"body,omitempty"`
}

// NewGetJwkOK creates GetJwkOK with default headers values
func NewGetJwkOK() *GetJwkOK {

	return &GetJwkOK{}
}

// WithPayload adds the payload to the get jwk o k response
func (o *GetJwkOK) WithPayload(payload *GetJwkOKBody) *GetJwkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get jwk o k response
func (o *GetJwkOK) SetPayload(payload *GetJwkOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJwkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetJwkInternalServerErrorCode is the HTTP code returned for type GetJwkInternalServerError
const GetJwkInternalServerErrorCode int = 500

/*GetJwkInternalServerError Internal server error

swagger:response getJwkInternalServerError
*/
type GetJwkInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *GetJwkInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetJwkInternalServerError creates GetJwkInternalServerError with default headers values
func NewGetJwkInternalServerError() *GetJwkInternalServerError {

	return &GetJwkInternalServerError{}
}

// WithPayload adds the payload to the get jwk internal server error response
func (o *GetJwkInternalServerError) WithPayload(payload *GetJwkInternalServerErrorBody) *GetJwkInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get jwk internal server error response
func (o *GetJwkInternalServerError) SetPayload(payload *GetJwkInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJwkInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
