version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: profile_mongodb
    ports:
      - 27017:27017
    networks:
      - diacare
    volumes:
      - 'mongo:/data/db'

  profile:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: profile_server
    environment:
      - PROFILE_LOGGING_OUTPUT=STDOUT
      - PROFILE_LOGGING_FORMAT=TEXT
      - PROFILE_LOGGING_LEVEL=INFO
      - PROFILE_HTTP_PORT=80
      - PROFILE_DB_PORT=27017
      - PROFILE_DB_HOST=profile_mongodb
      - PROFILE_DB_DATABASE=profile
      - PROFILE_SENTRYDSN=https://0c61099b61fe45bab898aa281fd3e5a1@sentry.diacare-soft.ru/29
    ports:
      - 9898:80
    networks:
      - diacare
    tty: true
    depends_on:
      - mongodb

networks:
  diacare:
    external: true
volumes:
  mongo: