// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSearchDepartmentsParams creates a new GetSearchDepartmentsParams object
// with the default values initialized.
func NewGetSearchDepartmentsParams() *GetSearchDepartmentsParams {
	var ()
	return &GetSearchDepartmentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSearchDepartmentsParamsWithTimeout creates a new GetSearchDepartmentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSearchDepartmentsParamsWithTimeout(timeout time.Duration) *GetSearchDepartmentsParams {
	var ()
	return &GetSearchDepartmentsParams{

		timeout: timeout,
	}
}

// NewGetSearchDepartmentsParamsWithContext creates a new GetSearchDepartmentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSearchDepartmentsParamsWithContext(ctx context.Context) *GetSearchDepartmentsParams {
	var ()
	return &GetSearchDepartmentsParams{

		Context: ctx,
	}
}

// NewGetSearchDepartmentsParamsWithHTTPClient creates a new GetSearchDepartmentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSearchDepartmentsParamsWithHTTPClient(client *http.Client) *GetSearchDepartmentsParams {
	var ()
	return &GetSearchDepartmentsParams{
		HTTPClient: client,
	}
}

/*GetSearchDepartmentsParams contains all the parameters to send to the API endpoint
for the get search departments operation typically these are written to a http.Request
*/
type GetSearchDepartmentsParams struct {

	/*Archived
	  Состояние записи

	*/
	Archived *bool
	/*ClinicGUID
	  GUID клиники

	*/
	ClinicGUID *string
	/*Limit
	  Лимит выдачи

	*/
	Limit *int64
	/*Offset
	  Шаг выдачи

	*/
	Offset *int64
	/*Type
	  Тип

	*/
	Type *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get search departments params
func (o *GetSearchDepartmentsParams) WithTimeout(timeout time.Duration) *GetSearchDepartmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get search departments params
func (o *GetSearchDepartmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get search departments params
func (o *GetSearchDepartmentsParams) WithContext(ctx context.Context) *GetSearchDepartmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get search departments params
func (o *GetSearchDepartmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get search departments params
func (o *GetSearchDepartmentsParams) WithHTTPClient(client *http.Client) *GetSearchDepartmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get search departments params
func (o *GetSearchDepartmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArchived adds the archived to the get search departments params
func (o *GetSearchDepartmentsParams) WithArchived(archived *bool) *GetSearchDepartmentsParams {
	o.SetArchived(archived)
	return o
}

// SetArchived adds the archived to the get search departments params
func (o *GetSearchDepartmentsParams) SetArchived(archived *bool) {
	o.Archived = archived
}

// WithClinicGUID adds the clinicGUID to the get search departments params
func (o *GetSearchDepartmentsParams) WithClinicGUID(clinicGUID *string) *GetSearchDepartmentsParams {
	o.SetClinicGUID(clinicGUID)
	return o
}

// SetClinicGUID adds the clinicGuid to the get search departments params
func (o *GetSearchDepartmentsParams) SetClinicGUID(clinicGUID *string) {
	o.ClinicGUID = clinicGUID
}

// WithLimit adds the limit to the get search departments params
func (o *GetSearchDepartmentsParams) WithLimit(limit *int64) *GetSearchDepartmentsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get search departments params
func (o *GetSearchDepartmentsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get search departments params
func (o *GetSearchDepartmentsParams) WithOffset(offset *int64) *GetSearchDepartmentsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get search departments params
func (o *GetSearchDepartmentsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithType adds the typeVar to the get search departments params
func (o *GetSearchDepartmentsParams) WithType(typeVar *int64) *GetSearchDepartmentsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get search departments params
func (o *GetSearchDepartmentsParams) SetType(typeVar *int64) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetSearchDepartmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Archived != nil {

		// query param archived
		var qrArchived bool
		if o.Archived != nil {
			qrArchived = *o.Archived
		}
		qArchived := swag.FormatBool(qrArchived)
		if qArchived != "" {
			if err := r.SetQueryParam("archived", qArchived); err != nil {
				return err
			}
		}

	}

	if o.ClinicGUID != nil {

		// query param clinicGUID
		var qrClinicGUID string
		if o.ClinicGUID != nil {
			qrClinicGUID = *o.ClinicGUID
		}
		qClinicGUID := qrClinicGUID
		if qClinicGUID != "" {
			if err := r.SetQueryParam("clinicGUID", qClinicGUID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Type != nil {

		// query param type
		var qrType int64
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := swag.FormatInt64(qrType)
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
