// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSearchClinicsParams creates a new GetSearchClinicsParams object
// with the default values initialized.
func NewGetSearchClinicsParams() *GetSearchClinicsParams {
	var ()
	return &GetSearchClinicsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSearchClinicsParamsWithTimeout creates a new GetSearchClinicsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSearchClinicsParamsWithTimeout(timeout time.Duration) *GetSearchClinicsParams {
	var ()
	return &GetSearchClinicsParams{

		timeout: timeout,
	}
}

// NewGetSearchClinicsParamsWithContext creates a new GetSearchClinicsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSearchClinicsParamsWithContext(ctx context.Context) *GetSearchClinicsParams {
	var ()
	return &GetSearchClinicsParams{

		Context: ctx,
	}
}

// NewGetSearchClinicsParamsWithHTTPClient creates a new GetSearchClinicsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSearchClinicsParamsWithHTTPClient(client *http.Client) *GetSearchClinicsParams {
	var ()
	return &GetSearchClinicsParams{
		HTTPClient: client,
	}
}

/*GetSearchClinicsParams contains all the parameters to send to the API endpoint
for the get search clinics operation typically these are written to a http.Request
*/
type GetSearchClinicsParams struct {

	/*Archived
	  Состояние записи

	*/
	Archived *bool
	/*Limit
	  Лимит выдачи

	*/
	Limit *int64
	/*Name
	  Название

	*/
	Name *string
	/*Offset
	  Шаг выдачи

	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get search clinics params
func (o *GetSearchClinicsParams) WithTimeout(timeout time.Duration) *GetSearchClinicsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get search clinics params
func (o *GetSearchClinicsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get search clinics params
func (o *GetSearchClinicsParams) WithContext(ctx context.Context) *GetSearchClinicsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get search clinics params
func (o *GetSearchClinicsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get search clinics params
func (o *GetSearchClinicsParams) WithHTTPClient(client *http.Client) *GetSearchClinicsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get search clinics params
func (o *GetSearchClinicsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArchived adds the archived to the get search clinics params
func (o *GetSearchClinicsParams) WithArchived(archived *bool) *GetSearchClinicsParams {
	o.SetArchived(archived)
	return o
}

// SetArchived adds the archived to the get search clinics params
func (o *GetSearchClinicsParams) SetArchived(archived *bool) {
	o.Archived = archived
}

// WithLimit adds the limit to the get search clinics params
func (o *GetSearchClinicsParams) WithLimit(limit *int64) *GetSearchClinicsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get search clinics params
func (o *GetSearchClinicsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the get search clinics params
func (o *GetSearchClinicsParams) WithName(name *string) *GetSearchClinicsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get search clinics params
func (o *GetSearchClinicsParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the get search clinics params
func (o *GetSearchClinicsParams) WithOffset(offset *int64) *GetSearchClinicsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get search clinics params
func (o *GetSearchClinicsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetSearchClinicsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Archived != nil {

		// query param archived
		var qrArchived bool
		if o.Archived != nil {
			qrArchived = *o.Archived
		}
		qArchived := swag.FormatBool(qrArchived)
		if qArchived != "" {
			if err := r.SetQueryParam("archived", qArchived); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
