apiVersion: v1
kind: Secret
metadata:
 name: {{ include "mailer.fullname" . }}
 labels:
   app.kubernetes.io/name: {{ include "mailer.fullname" . }}
   app.kubernetes.io/managed-by: "helm"
   app.kubernetes.io/part-of: "maximus"
   helm.sh/chart: {{ include "mailer.name" . }}-{{ include "mailer.release" . }}
   helm.sh/hook: "pre-install"
data:
  MAILER_EVENTDB_PASSWORD: {{ default .Values.defaults.secrets.MAILER_EVENTDB_PASSWORD .Values.MAILER_EVENTDB_PASSWORD | b64enc }}
  MAILER_CONFIGDB_PASSWORD: {{ default .Values.defaults.secrets.MAILER_CONFIGDB_PASSWORD .Values.MAILER_CONFIGDB_PASSWORD | b64enc }}
  MAILER_MASTERTOKEN: {{ default .Values.defaults.secrets.MAILER_MASTERTOKEN .Values.MAILER_MASTERTOKEN | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
 name: {{ include "mailer.fullname" . }}
 namespace: databases
 labels:
   app.kubernetes.io/name: {{ include "mailer.fullname" . }}
   app.kubernetes.io/managed-by: "helm"
   app.kubernetes.io/part-of: "maximus"
   helm.sh/chart: {{ include "mailer.name" . }}-{{ include "mailer.release" . }}
   helm.sh/hook: "pre-install"
data:
  MAILER_EVENTDB_PASSWORD: {{ default .Values.defaults.secrets.MAILER_EVENTDB_PASSWORD .Values.MAILER_EVENTDB_PASSWORD | b64enc }}
  MAILER_CONFIGDB_PASSWORD: {{ default .Values.defaults.secrets.MAILER_CONFIGDB_PASSWORD .Values.MAILER_CONFIGDB_PASSWORD | b64enc }}
type: Opaque
