apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mailer.fullname" . }}
    app.kubernetes.io/managed-by: "helm"
    app.kubernetes.io/part-of: "maximus"
    helm.sh/chart: {{ include "mailer.name" . }}-{{ include "mailer.release" . }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
  - name: {{ include "mailer.name" . }}
    port: {{ .Values.MAILER_HTTP_PORT | default .Values.defaults.env.MAILER_HTTP_PORT }}
    targetPort: {{ .Values.MAILER_HTTP_PORT | default .Values.defaults.env.MAILER_HTTP_PORT }}
    protocol: TCP
  - name: {{ include "mailer.name" . }}-metrics
    port: {{ .Values.MAILER_PROMETHEUS_PORT | default .Values.defaults.env.MAILER_PROMETHEUS_PORT }}
    targetPort: {{ .Values.MAILER_PROMETHEUS_PORT | default .Values.defaults.env.MAILER_PROMETHEUS_PORT }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mailer.fullname" . }}
