// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"repo.nefrosovet.ru/go-lms/api-video/ent/accountkey"
	"repo.nefrosovet.ru/go-lms/api-video/ent/predicate"
	"repo.nefrosovet.ru/go-lms/api-video/ent/useraccount"
)

// AccountKeyQuery is the builder for querying AccountKey entities.
type AccountKeyQuery struct {
	config
	limit      *int
	offset     *int
	order      []Order
	unique     []string
	predicates []predicate.AccountKey
	// eager-loading edges.
	withUseraccount *UserAccountQuery
	withFKs         bool
	// intermediate query.
	sql *sql.Selector
}

// Where adds a new predicate for the builder.
func (akq *AccountKeyQuery) Where(ps ...predicate.AccountKey) *AccountKeyQuery {
	akq.predicates = append(akq.predicates, ps...)
	return akq
}

// Limit adds a limit step to the query.
func (akq *AccountKeyQuery) Limit(limit int) *AccountKeyQuery {
	akq.limit = &limit
	return akq
}

// Offset adds an offset step to the query.
func (akq *AccountKeyQuery) Offset(offset int) *AccountKeyQuery {
	akq.offset = &offset
	return akq
}

// Order adds an order step to the query.
func (akq *AccountKeyQuery) Order(o ...Order) *AccountKeyQuery {
	akq.order = append(akq.order, o...)
	return akq
}

// QueryUseraccount chains the current query on the useraccount edge.
func (akq *AccountKeyQuery) QueryUseraccount() *UserAccountQuery {
	query := &UserAccountQuery{config: akq.config}
	step := sqlgraph.NewStep(
		sqlgraph.From(accountkey.Table, accountkey.FieldID, akq.sqlQuery()),
		sqlgraph.To(useraccount.Table, useraccount.FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, accountkey.UseraccountTable, accountkey.UseraccountColumn),
	)
	query.sql = sqlgraph.SetNeighbors(akq.driver.Dialect(), step)
	return query
}

// First returns the first AccountKey entity in the query. Returns *NotFoundError when no accountkey was found.
func (akq *AccountKeyQuery) First(ctx context.Context) (*AccountKey, error) {
	aks, err := akq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(aks) == 0 {
		return nil, &NotFoundError{accountkey.Label}
	}
	return aks[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (akq *AccountKeyQuery) FirstX(ctx context.Context) *AccountKey {
	ak, err := akq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return ak
}

// FirstID returns the first AccountKey id in the query. Returns *NotFoundError when no id was found.
func (akq *AccountKeyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = akq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accountkey.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (akq *AccountKeyQuery) FirstXID(ctx context.Context) int {
	id, err := akq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only AccountKey entity in the query, returns an error if not exactly one entity was returned.
func (akq *AccountKeyQuery) Only(ctx context.Context) (*AccountKey, error) {
	aks, err := akq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(aks) {
	case 1:
		return aks[0], nil
	case 0:
		return nil, &NotFoundError{accountkey.Label}
	default:
		return nil, &NotSingularError{accountkey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (akq *AccountKeyQuery) OnlyX(ctx context.Context) *AccountKey {
	ak, err := akq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return ak
}

// OnlyID returns the only AccountKey id in the query, returns an error if not exactly one id was returned.
func (akq *AccountKeyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = akq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accountkey.Label}
	default:
		err = &NotSingularError{accountkey.Label}
	}
	return
}

// OnlyXID is like OnlyID, but panics if an error occurs.
func (akq *AccountKeyQuery) OnlyXID(ctx context.Context) int {
	id, err := akq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccountKeys.
func (akq *AccountKeyQuery) All(ctx context.Context) ([]*AccountKey, error) {
	return akq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (akq *AccountKeyQuery) AllX(ctx context.Context) []*AccountKey {
	aks, err := akq.All(ctx)
	if err != nil {
		panic(err)
	}
	return aks
}

// IDs executes the query and returns a list of AccountKey ids.
func (akq *AccountKeyQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := akq.Select(accountkey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (akq *AccountKeyQuery) IDsX(ctx context.Context) []int {
	ids, err := akq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (akq *AccountKeyQuery) Count(ctx context.Context) (int, error) {
	return akq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (akq *AccountKeyQuery) CountX(ctx context.Context) int {
	count, err := akq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (akq *AccountKeyQuery) Exist(ctx context.Context) (bool, error) {
	return akq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (akq *AccountKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := akq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (akq *AccountKeyQuery) Clone() *AccountKeyQuery {
	return &AccountKeyQuery{
		config:     akq.config,
		limit:      akq.limit,
		offset:     akq.offset,
		order:      append([]Order{}, akq.order...),
		unique:     append([]string{}, akq.unique...),
		predicates: append([]predicate.AccountKey{}, akq.predicates...),
		// clone intermediate query.
		sql: akq.sql.Clone(),
	}
}

//  WithUseraccount tells the query-builder to eager-loads the nodes that are connected to
// the "useraccount" edge. The optional arguments used to configure the query builder of the edge.
func (akq *AccountKeyQuery) WithUseraccount(opts ...func(*UserAccountQuery)) *AccountKeyQuery {
	query := &UserAccountQuery{config: akq.config}
	for _, opt := range opts {
		opt(query)
	}
	akq.withUseraccount = query
	return akq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccountKey.Query().
//		GroupBy(accountkey.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (akq *AccountKeyQuery) GroupBy(field string, fields ...string) *AccountKeyGroupBy {
	group := &AccountKeyGroupBy{config: akq.config}
	group.fields = append([]string{field}, fields...)
	group.sql = akq.sqlQuery()
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AccountKey.Query().
//		Select(accountkey.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (akq *AccountKeyQuery) Select(field string, fields ...string) *AccountKeySelect {
	selector := &AccountKeySelect{config: akq.config}
	selector.fields = append([]string{field}, fields...)
	selector.sql = akq.sqlQuery()
	return selector
}

func (akq *AccountKeyQuery) sqlAll(ctx context.Context) ([]*AccountKey, error) {
	var (
		nodes       = []*AccountKey{}
		withFKs     = akq.withFKs
		_spec       = akq.querySpec()
		loadedTypes = [1]bool{
			akq.withUseraccount != nil,
		}
	)
	if akq.withUseraccount != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, accountkey.ForeignKeys...)
	}
	_spec.ScanValues = func() []interface{} {
		node := &AccountKey{config: akq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		if withFKs {
			values = append(values, node.fkValues()...)
		}
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, akq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := akq.withUseraccount; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*AccountKey)
		for i := range nodes {
			if fk := nodes[i].user_account_accountkeys; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(useraccount.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_account_accountkeys" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Useraccount = n
			}
		}
	}

	return nodes, nil
}

func (akq *AccountKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := akq.querySpec()
	return sqlgraph.CountNodes(ctx, akq.driver, _spec)
}

func (akq *AccountKeyQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := akq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (akq *AccountKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accountkey.Table,
			Columns: accountkey.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accountkey.FieldID,
			},
		},
		From:   akq.sql,
		Unique: true,
	}
	if ps := akq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := akq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := akq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := akq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (akq *AccountKeyQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(akq.driver.Dialect())
	t1 := builder.Table(accountkey.Table)
	selector := builder.Select(t1.Columns(accountkey.Columns...)...).From(t1)
	if akq.sql != nil {
		selector = akq.sql
		selector.Select(selector.Columns(accountkey.Columns...)...)
	}
	for _, p := range akq.predicates {
		p(selector)
	}
	for _, p := range akq.order {
		p(selector)
	}
	if offset := akq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := akq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccountKeyGroupBy is the builder for group-by AccountKey entities.
type AccountKeyGroupBy struct {
	config
	fields []string
	fns    []Aggregate
	// intermediate query.
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the group-by query.
func (akgb *AccountKeyGroupBy) Aggregate(fns ...Aggregate) *AccountKeyGroupBy {
	akgb.fns = append(akgb.fns, fns...)
	return akgb
}

// Scan applies the group-by query and scan the result into the given value.
func (akgb *AccountKeyGroupBy) Scan(ctx context.Context, v interface{}) error {
	return akgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (akgb *AccountKeyGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := akgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (akgb *AccountKeyGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(akgb.fields) > 1 {
		return nil, errors.New("ent: AccountKeyGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := akgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (akgb *AccountKeyGroupBy) StringsX(ctx context.Context) []string {
	v, err := akgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (akgb *AccountKeyGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(akgb.fields) > 1 {
		return nil, errors.New("ent: AccountKeyGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := akgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (akgb *AccountKeyGroupBy) IntsX(ctx context.Context) []int {
	v, err := akgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (akgb *AccountKeyGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(akgb.fields) > 1 {
		return nil, errors.New("ent: AccountKeyGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := akgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (akgb *AccountKeyGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := akgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (akgb *AccountKeyGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(akgb.fields) > 1 {
		return nil, errors.New("ent: AccountKeyGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := akgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (akgb *AccountKeyGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := akgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (akgb *AccountKeyGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := akgb.sqlQuery().Query()
	if err := akgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (akgb *AccountKeyGroupBy) sqlQuery() *sql.Selector {
	selector := akgb.sql
	columns := make([]string, 0, len(akgb.fields)+len(akgb.fns))
	columns = append(columns, akgb.fields...)
	for _, fn := range akgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(akgb.fields...)
}

// AccountKeySelect is the builder for select fields of AccountKey entities.
type AccountKeySelect struct {
	config
	fields []string
	// intermediate queries.
	sql *sql.Selector
}

// Scan applies the selector query and scan the result into the given value.
func (aks *AccountKeySelect) Scan(ctx context.Context, v interface{}) error {
	return aks.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aks *AccountKeySelect) ScanX(ctx context.Context, v interface{}) {
	if err := aks.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (aks *AccountKeySelect) Strings(ctx context.Context) ([]string, error) {
	if len(aks.fields) > 1 {
		return nil, errors.New("ent: AccountKeySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := aks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aks *AccountKeySelect) StringsX(ctx context.Context) []string {
	v, err := aks.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (aks *AccountKeySelect) Ints(ctx context.Context) ([]int, error) {
	if len(aks.fields) > 1 {
		return nil, errors.New("ent: AccountKeySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := aks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aks *AccountKeySelect) IntsX(ctx context.Context) []int {
	v, err := aks.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (aks *AccountKeySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(aks.fields) > 1 {
		return nil, errors.New("ent: AccountKeySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := aks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aks *AccountKeySelect) Float64sX(ctx context.Context) []float64 {
	v, err := aks.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (aks *AccountKeySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(aks.fields) > 1 {
		return nil, errors.New("ent: AccountKeySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := aks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aks *AccountKeySelect) BoolsX(ctx context.Context) []bool {
	v, err := aks.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aks *AccountKeySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aks.sqlQuery().Query()
	if err := aks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aks *AccountKeySelect) sqlQuery() sql.Querier {
	selector := aks.sql
	selector.Select(selector.Columns(aks.fields...)...)
	return selector
}
