// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Error405DataAllOf1 Error_Error_405_data
// swagger:model error405DataAllOf1
type Error405DataAllOf1 struct {

	// код ответа
	Code int64 `json:"code,omitempty"`

	// сообщение ответа
	Message string `json:"message,omitempty"`
}

// Validate validates this error405 data all of1
func (m *Error405DataAllOf1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Error405DataAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Error405DataAllOf1) UnmarshalBinary(b []byte) error {
	var res Error405DataAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
