// Code generated by go-swagger; DO NOT EDIT.

package clinic_employees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClinicsClinicGUIDEmployeesParams creates a new GetClinicsClinicGUIDEmployeesParams object
// with the default values initialized.
func NewGetClinicsClinicGUIDEmployeesParams() *GetClinicsClinicGUIDEmployeesParams {
	var ()
	return &GetClinicsClinicGUIDEmployeesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetClinicsClinicGUIDEmployeesParamsWithTimeout creates a new GetClinicsClinicGUIDEmployeesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetClinicsClinicGUIDEmployeesParamsWithTimeout(timeout time.Duration) *GetClinicsClinicGUIDEmployeesParams {
	var ()
	return &GetClinicsClinicGUIDEmployeesParams{

		timeout: timeout,
	}
}

// NewGetClinicsClinicGUIDEmployeesParamsWithContext creates a new GetClinicsClinicGUIDEmployeesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetClinicsClinicGUIDEmployeesParamsWithContext(ctx context.Context) *GetClinicsClinicGUIDEmployeesParams {
	var ()
	return &GetClinicsClinicGUIDEmployeesParams{

		Context: ctx,
	}
}

// NewGetClinicsClinicGUIDEmployeesParamsWithHTTPClient creates a new GetClinicsClinicGUIDEmployeesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetClinicsClinicGUIDEmployeesParamsWithHTTPClient(client *http.Client) *GetClinicsClinicGUIDEmployeesParams {
	var ()
	return &GetClinicsClinicGUIDEmployeesParams{
		HTTPClient: client,
	}
}

/*GetClinicsClinicGUIDEmployeesParams contains all the parameters to send to the API endpoint
for the get clinics clinic GUID employees operation typically these are written to a http.Request
*/
type GetClinicsClinicGUIDEmployeesParams struct {

	/*ClinicGUID
	  GUID клиники

	*/
	ClinicGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get clinics clinic GUID employees params
func (o *GetClinicsClinicGUIDEmployeesParams) WithTimeout(timeout time.Duration) *GetClinicsClinicGUIDEmployeesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get clinics clinic GUID employees params
func (o *GetClinicsClinicGUIDEmployeesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get clinics clinic GUID employees params
func (o *GetClinicsClinicGUIDEmployeesParams) WithContext(ctx context.Context) *GetClinicsClinicGUIDEmployeesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get clinics clinic GUID employees params
func (o *GetClinicsClinicGUIDEmployeesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get clinics clinic GUID employees params
func (o *GetClinicsClinicGUIDEmployeesParams) WithHTTPClient(client *http.Client) *GetClinicsClinicGUIDEmployeesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get clinics clinic GUID employees params
func (o *GetClinicsClinicGUIDEmployeesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClinicGUID adds the clinicGUID to the get clinics clinic GUID employees params
func (o *GetClinicsClinicGUIDEmployeesParams) WithClinicGUID(clinicGUID string) *GetClinicsClinicGUIDEmployeesParams {
	o.SetClinicGUID(clinicGUID)
	return o
}

// SetClinicGUID adds the clinicGuid to the get clinics clinic GUID employees params
func (o *GetClinicsClinicGUIDEmployeesParams) SetClinicGUID(clinicGUID string) {
	o.ClinicGUID = clinicGUID
}

// WriteToRequest writes these params to a swagger request
func (o *GetClinicsClinicGUIDEmployeesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clinicGUID
	if err := r.SetPathParam("clinicGUID", o.ClinicGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
