// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAdminOKCode is the HTTP code returned for type PostAdminOK
const PostAdminOKCode int = 200

/*PostAdminOK SUCCESS

swagger:response postAdminOK
*/
type PostAdminOK struct {

	/*
	  In: Body
	*/
	Payload *PostAdminOKBody `json:"body,omitempty"`
}

// NewPostAdminOK creates PostAdminOK with default headers values
func NewPostAdminOK() *PostAdminOK {

	return &PostAdminOK{}
}

// WithPayload adds the payload to the post admin o k response
func (o *PostAdminOK) WithPayload(payload *PostAdminOKBody) *PostAdminOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post admin o k response
func (o *PostAdminOK) SetPayload(payload *PostAdminOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdminOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdminBadRequestCode is the HTTP code returned for type PostAdminBadRequest
const PostAdminBadRequestCode int = 400

/*PostAdminBadRequest Коллекция авторизации

swagger:response postAdminBadRequest
*/
type PostAdminBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PostAdminBadRequestBody `json:"body,omitempty"`
}

// NewPostAdminBadRequest creates PostAdminBadRequest with default headers values
func NewPostAdminBadRequest() *PostAdminBadRequest {

	return &PostAdminBadRequest{}
}

// WithPayload adds the payload to the post admin bad request response
func (o *PostAdminBadRequest) WithPayload(payload *PostAdminBadRequestBody) *PostAdminBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post admin bad request response
func (o *PostAdminBadRequest) SetPayload(payload *PostAdminBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdminBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdminMethodNotAllowedCode is the HTTP code returned for type PostAdminMethodNotAllowed
const PostAdminMethodNotAllowedCode int = 405

/*PostAdminMethodNotAllowed Invalid Method

swagger:response postAdminMethodNotAllowed
*/
type PostAdminMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *PostAdminMethodNotAllowedBody `json:"body,omitempty"`
}

// NewPostAdminMethodNotAllowed creates PostAdminMethodNotAllowed with default headers values
func NewPostAdminMethodNotAllowed() *PostAdminMethodNotAllowed {

	return &PostAdminMethodNotAllowed{}
}

// WithPayload adds the payload to the post admin method not allowed response
func (o *PostAdminMethodNotAllowed) WithPayload(payload *PostAdminMethodNotAllowedBody) *PostAdminMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post admin method not allowed response
func (o *PostAdminMethodNotAllowed) SetPayload(payload *PostAdminMethodNotAllowedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdminMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdminInternalServerErrorCode is the HTTP code returned for type PostAdminInternalServerError
const PostAdminInternalServerErrorCode int = 500

/*PostAdminInternalServerError Internal server error

swagger:response postAdminInternalServerError
*/
type PostAdminInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostAdminInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostAdminInternalServerError creates PostAdminInternalServerError with default headers values
func NewPostAdminInternalServerError() *PostAdminInternalServerError {

	return &PostAdminInternalServerError{}
}

// WithPayload adds the payload to the post admin internal server error response
func (o *PostAdminInternalServerError) WithPayload(payload *PostAdminInternalServerErrorBody) *PostAdminInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post admin internal server error response
func (o *PostAdminInternalServerError) SetPayload(payload *PostAdminInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdminInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
