// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Mailer API
#### RESTFUL Mailer API



    Schemes:
      http
    Host: mailer.maximus.lan
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
