// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReplyObject Reply_object
// swagger:model Reply_object
type ReplyObject struct {

	// Описание шаблона
	Description string `json:"description,omitempty"`

	// Regex шаблона
	// Required: true
	Regex *string `json:"regex"`

	// Regex шаблона
	// Required: true
	Replace *string `json:"replace"`
}

// Validate validates this reply object
func (m *ReplyObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRegex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReplace(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReplyObject) validateRegex(formats strfmt.Registry) error {

	if err := validate.Required("regex", "body", m.Regex); err != nil {
		return err
	}

	return nil
}

func (m *ReplyObject) validateReplace(formats strfmt.Registry) error {

	if err := validate.Required("replace", "body", m.Replace); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReplyObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReplyObject) UnmarshalBinary(b []byte) error {
	var res ReplyObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
